### ISSUE TITLE
filter_precedence()

### ISSUE THREAD

**Issue by larspijnappel** [gertjanssenswillen/edeaR#16]
The `filter_precedence()` function puzzles me quite a bit (even after reading the available documentation).

When using this function, before creating a `process_map()`, I would expect to see the same number of events as is listed in the `precedence_matrix()`. However, that's not the case.

According to `patients %>% precedence_matrix() %>% plot()`, there are 492 cases/events between __Discuss Results__ and __Check-out__. 
However, running `patients %>% filter_precedence("Discuss Results", "Check-out") %>% case_labels()` shows only 3 cases. 

After further analysis it appears that one must use the argument `filter_method = "none"` to achieve the expected outcome: getting only those case which do have these precedence activities included in their trace. Forgetting this argument results in an, for me unintended and unexpected, outcome (which actually shows the opposite: cases having _not_ the provided filter argument).

So my question is: could this be a bug or am I misunderstanding the purpose of this function?

Thx!

**Comment by gertjanssenswillen** [comment]
Sorry for the delay. This seems to be a bug indeaad. I'll try to fix it asap.

Thanks for noticing!

**Comment by gertjanssenswillen** [comment]
Committed changes to github to fix this bug. Filter should now work as expected.

**Comment by larspijnappel** [comment]
Hi Gert,

My packageVersion("edeaR") states ‘0.8.0’, but I still have the same wrong results as mentioned in the original post. So, the argument `filter_method = "none"` is still needed.

As a side note:
I also noticed a discrepancy in the help section for the `filter_method` argument (stating the possible values `each` and `one_of`). However `each` is not accepted and, and luckily, the correct values are returned back in the error message.

Thx again!

**Comment by gertjanssenswillen** [comment]
I'll check.

**Comment by gertjanssenswillen** [comment]
Filter should work properly, only thing I found was a missing dependency to stringr. Could you check again? Version after installing from github should now be 0.8.0.9000.

Also, incorrect docs update, thanks for noticing.

**Comment by larspijnappel** [comment]
Yes, now it works like a charm. 
Thx also for your guick feedback: now I can start unleashing the power of process mining.

:+1:  bupaR rocks!! :+1:
